---
- name: Order AMAPDUPL PTF.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:
  
    - name: Order jcl.
      ibm.ibm_zos_core.zos_job_submit:
        location: LOCAL
        src: templates/order.jcl.j2
        use_template: true
        wait_time_s: 1000
        encoding:
          from: UTF-8
          to: IBM-037
      register: order

    - name: Print JCL.
      ansible.builtin.debug:
        msg: "{{ order.content }}"
