---
- name: Add new RACF user and map identity
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:
  
    - name: Add new userID and connect to groups
      ibm.ibm_zos_core.zos_tso_command:
        commands: 
          - "AU {{ new_userid }} DFLTGRP(UGROUP) TSO(ACCTNUM(*) PROC(IZUFPROC) SIZE(2096128))"
          - "PW USER({{ new_userid }}) NOINTERVAL"
          - "ALU {{ new_userid }} PASSWORD({{ new_password }}) OMVS(UID(0) SHARED)"
          - "CO ({{ new_userid }}) GROUP(IZUADMIN)"
          #- "CO ({{ new_userid }}) GROUP(WLMGRP)"
          - "CO ({{ new_userid }}) GROUP(CFZADMGP)"
          #- "CO ({{ new_userid }}) GROUP(OMVSGRP)"
        max_rc: 4

    #- name: MODIFY IKJTSO00 member of SYS1.PARMLIB to include a line for RACMAP command in AUTHCMD
    #- name: Operator command to run: SET IKJTSO=00

    - name: Map identity to email address
      ibm.ibm_zos_core.zos_tso_command:
        command: "RACMAP ID({{ new_userid }}) MAP USERDIDFILTER(NAME('{{ new_email }}')) REGISTRY(NAME('ldaps://bluepages.ibm.com')) WITHLABEL('{{ new_userid }} ON BLUEPAGES')"
        max_rc: 4

    #- name: STERPTS COMMAND TO TAKE AFFECT
