---
# Copyright (c) IBM Corporation 2021

# tasks file for reject_ptf

# REJECT CHECK a SYSMOD
- name: "REJECT CHECK ALL RECEIVED-ONLY SYSMODS"
  ibm.ibm_zos_core.zos_mvs_raw:
    pgm: GIMSMP
    auth: "yes"
    dds:
      - dd_data_set:
          dd_name: "SMPCSI"
          data_set_name: "SMPE.PROGPROD.CSI"
          disposition: old

      - dd_output:
          dd_name: "SMPOUT"
          return_content:
            type: text
      - dd_input:
          dd_name: "SMPCNTL"
          content: " SET  BOUNDARY(GLOBAL) .
                    \nREJECT CHECK PTFS."
  register: reject_check_result

# REJECT a SYSMOD
- name: "REJECT ALL RECEIVED-ONLY SYSMODS"
  ibm.ibm_zos_core.zos_mvs_raw:
    pgm: GIMSMP
    auth: "yes"
    dds:
      - dd_data_set:
          dd_name: "SMPCSI"
          data_set_name: "SMPE.PROGPROD.CSI"
          disposition: old

      - dd_output:
          dd_name: "SMPOUT"
          return_content:
            type: text
      - dd_input:
          dd_name: "SMPCNTL"
          content: " SET  BOUNDARY(GLOBAL) .
                    \nREJECT PTFS
                    \nAPARS
                    \nFUNCTIONS
                    \nUSERMODS."
  tags: reject sysmod
  when: reject_check_result.ret_code.code <= 4
